version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    command: ["-js"]

  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"

  lambda:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=testUser
      - AWS_SECRET_ACCESS_KEY=testAccessKey
      - LAMBDA_EXECUTOR=local
  
  jetbridge_init:
    build:
      context: ../..
      dockerfile: Dockerfile.server
    command: ["create-table"]
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=testUser
      - AWS_SECRET_ACCESS_KEY=testAccessKey
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    depends_on:
      dynamodb:
        condition: service_started

  jetbridge:
    build:
      context: ../..
      dockerfile: Dockerfile.server
    command: ["serve"]
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=testUser
      - AWS_SECRET_ACCESS_KEY=testAccessKey
      - NATS_URL=nats://nats:4222
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - LAMBDA_ENDPOINT=http://lambda:4566
    ports:
      - "8080:8080"
    depends_on:
      nats:
        condition: service_started
      dynamodb:
        condition: service_started
      lambda:
        condition: service_started
      jetbridge_init:
        condition: service_completed_successfully

 
